
openapi: '3.0.2'
info:
  title: Test API
  version: '1.0'

paths:
  /recipients/{id}:
    get:
      description: Returns single recipient
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  folders:
                    type: array
                    items:
                      $ref: '#/components/schemas/Recipient'

components:
  schemas:
    Recipient:
      type: object
      properties:
        name:
          type: string
          example: "John Doe"
        email:
          type: string
          example: "john.doe@example.com"
