
openapi: '3.0.2'
info:
  title: Test API
  version: '1.0'

paths:
  /recipients/{id}:
    get:
      operationId: "getRecipientById"
      description: Returns single recipient
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            example: abcdef1234
            minLength: 1

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  recipient:
                      $ref: '#/components/schemas/Recipient'

components:
  schemas:
    Recipient:
      type: object
      properties:
        id:
          type: string
          example: abcdef1234
          minLength: 1
        name:
          type: string
          example: "John Doe"
        email:
          type: string
          example: "john.doe@example.com"
